<?php

/**
 * This is the model base class for the table "empresa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empresa".
 *
 * Columns in table "empresa" available as properties of the model,
 * followed by relations of table "empresa" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $dir_calleprin
 * @property string $dir_callesec
 * @property string $dir_ncasa
 * @property string $telefono
 * @property string $estado
 *
 * @property RepVinculacion[] $repVinculacions
 */
abstract class BaseEmpresa extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'empresa';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, dir_calleprin, dir_callesec, telefono', 'required'),
            array('nombre', 'length', 'max'=>100),
            array('descripcion', 'length', 'max'=>300),
            array('dir_calleprin, dir_callesec', 'length', 'max'=>50),
            array('dir_ncasa', 'length', 'max'=>10),
            array('telefono', 'length', 'max'=>20),
            array('estado', 'length', 'max'=>8),
            array('descripcion, dir_ncasa, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, descripcion, dir_calleprin, dir_callesec, dir_ncasa, telefono, estado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'repVinculacions' => array(self::HAS_MANY, 'RepVinculacion', 'id_empresa'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'dir_calleprin' => Yii::t('app', 'Dir Calleprin'),
                'dir_callesec' => Yii::t('app', 'Dir Callesec'),
                'dir_ncasa' => Yii::t('app', 'Dir Ncasa'),
                'telefono' => Yii::t('app', 'Telefono'),
                'estado' => Yii::t('app', 'Estado'),
                'repVinculacions' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('dir_calleprin', $this->dir_calleprin, true);
        $criteria->compare('dir_callesec', $this->dir_callesec, true);
        $criteria->compare('dir_ncasa', $this->dir_ncasa, true);
        $criteria->compare('telefono', $this->telefono, true);
        $criteria->compare('estado', $this->estado, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}